services:
  - type: web
    name: drive-clone-backend
    env: docker
    plan: free
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_FILE_UPLOAD_DIR
        value: /app/uploads
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
